package types

import (
	"github.com/lyraproj/puppet-evaluator/eval"
	"reflect"
	"time"
)

// This init function must be run last in the type package. Hence the file name
func init() {
	primitivePTypes = map[reflect.Kind]eval.Type{
		reflect.String:  DefaultStringType(),
		reflect.Int:     DefaultIntegerType(),
		reflect.Int8:    integerType8,
		reflect.Int16:   integerType16,
		reflect.Int32:   integerType32,
		reflect.Int64:   DefaultIntegerType(),
		reflect.Uint:    integerTypeU64,
		reflect.Uint8:   integerTypeU8,
		reflect.Uint16:  integerTypeU16,
		reflect.Uint32:  integerTypeU32,
		reflect.Uint64:  integerTypeU64,
		reflect.Float32: floatType32,
		reflect.Float64: DefaultFloatType(),
		reflect.Bool:    DefaultBooleanType(),
	}

	coreTypes = map[string]eval.Type{
		`Annotation`:    DefaultAnnotationType(),
		`Any`:           DefaultAnyType(),
		`Array`:         DefaultArrayType(),
		`Binary`:        DefaultBinaryType(),
		`Boolean`:       DefaultBooleanType(),
		`Callable`:      DefaultCallableType(),
		`Collection`:    DefaultCollectionType(),
		`Data`:          DefaultDataType(),
		`Default`:       DefaultDefaultType(),
		`Enum`:          DefaultEnumType(),
		`Float`:         DefaultFloatType(),
		`Hash`:          DefaultHashType(),
		`Init`:          DefaultInitType(),
		`Integer`:       DefaultIntegerType(),
		`Iterable`:      DefaultIterableType(),
		`Iterator`:      DefaultIteratorType(),
		`Like`:          DefaultLikeType(),
		`Notundef`:      DefaultNotUndefType(),
		`NotUndef`:      DefaultNotUndefType(),
		`Numeric`:       DefaultNumericType(),
		`Optional`:      DefaultOptionalType(),
		`Object`:        DefaultObjectType(),
		`Pattern`:       DefaultPatternType(),
		`Regexp`:        DefaultRegexpType(),
		`RegExp`:        DefaultRegexpType(),
		`Richdata`:      DefaultRichDataType(),
		`RichData`:      DefaultRichDataType(),
		`Runtime`:       DefaultRuntimeType(),
		`Scalardata`:    DefaultScalarDataType(),
		`ScalarData`:    DefaultScalarDataType(),
		`Scalar`:        DefaultScalarType(),
		`Semver`:        DefaultSemVerType(),
		`SemVer`:        DefaultSemVerType(),
		`Semverrange`:   DefaultSemVerRangeType(),
		`SemverRange`:   DefaultSemVerRangeType(),
		`SemVerRange`:   DefaultSemVerRangeType(),
		`Sensitive`:     DefaultSensitiveType(),
		`String`:        DefaultStringType(),
		`Struct`:        DefaultStructType(),
		`Timespan`:      DefaultTimespanType(),
		`TimeSpan`:      DefaultTimespanType(),
		`Timestamp`:     DefaultTimestampType(),
		`TimeStamp`:     DefaultTimestampType(),
		`Tuple`:         DefaultTupleType(),
		`Type`:          DefaultTypeType(),
		`Typealias`:     DefaultTypeAliasType(),
		`TypeAlias`:     DefaultTypeAliasType(),
		`Typereference`: DefaultTypeReferenceType(),
		`TypeReference`: DefaultTypeReferenceType(),
		`Typeset`:       DefaultTypeSetType(),
		`TypeSet`:       DefaultTypeSetType(),
		`Undef`:         DefaultUndefType(),
		`Unit`:          DefaultUnitType(),
		`Uri`:           DefaultUriType(),
		`URI`:           DefaultUriType(),
		`Variant`:       DefaultVariantType(),
	}

	wellKnown = map[reflect.Type]eval.Type{
		reflect.TypeOf(&ArrayValue{}):                    DefaultArrayType(),
		reflect.TypeOf((*eval.List)(nil)).Elem():         DefaultArrayType(),
		reflect.TypeOf(&BinaryValue{}):                   DefaultBinaryType(),
		reflect.TypeOf(floatValue(0.0)):                  DefaultFloatType(),
		reflect.TypeOf((*eval.FloatValue)(nil)).Elem():   DefaultFloatType(),
		reflect.TypeOf(&HashValue{}):                     DefaultHashType(),
		reflect.TypeOf((*eval.OrderedMap)(nil)).Elem():   DefaultHashType(),
		reflect.TypeOf(integerValue(0)):                  DefaultIntegerType(),
		reflect.TypeOf((*eval.IntegerValue)(nil)).Elem(): DefaultIntegerType(),
		reflect.TypeOf(&RegexpValue{}):                   DefaultRegexpType(),
		reflect.TypeOf(&SemVerValue{}):                   DefaultSemVerType(),
		reflect.TypeOf(&SensitiveValue{}):                DefaultSensitiveType(),
		reflect.TypeOf(stringValue(``)):                  DefaultStringType(),
		reflect.TypeOf((*eval.StringValue)(nil)).Elem():  DefaultStringType(),
		reflect.TypeOf(TimespanValue(0)):                 DefaultTimespanType(),
		reflect.TypeOf(time.Duration(0)):                 DefaultTimespanType(),
		reflect.TypeOf(time.Time{}):                      DefaultTimestampType(),
		reflect.TypeOf(&TimestampValue{}):                DefaultTimestampType(),
		evalValueType:                                    DefaultAnyType(),
		reflect.TypeOf((*eval.PuppetObject)(nil)).Elem(): DefaultObjectType(),
		reflect.TypeOf((*eval.Object)(nil)).Elem():       DefaultObjectType(),
		evalObjectTypeType:                               ObjectMetaType,
		reflect.TypeOf(&TypeType{}):                      DefaultTypeType(),
		evalTypeType:                                     DefaultTypeType(),
		reflect.TypeOf(&typeSet{}):                       TypeSetMetaType,
		evalTypeSetType:                                  TypeSetMetaType,
		reflect.TypeOf((*eval.TypedName)(nil)).Elem():    TypedNameMetaType,
		reflect.TypeOf(&UndefValue{}):                    DefaultUndefType(),
		reflect.TypeOf(&UriValue{}):                      DefaultUriType(),
	}
}
